# Generated by Django 2.0.1 on 2018-02-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20180207_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='player',
            name='group',
        ),
        migrations.AddField(
            model_name='participation',
            name='group',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1),
        ),
    ]
