# Generated by Django 2.0.1 on 2018-02-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20180207_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='race',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
