# Generated by Django 2.0.1 on 2018-02-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20180208_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='budget',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
