# Generated by Django 2.0.1 on 2018-03-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_participation_finish_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='finish_time',
        ),
    ]
