# Generated by Django 2.0.1 on 2018-03-04 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_remove_participation_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='finish_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
