# Generated by Django 2.0.1 on 2018-03-04 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_participation_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='ELITE_MAN_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='race',
            name='ELITE_WOMAN_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='race',
            name='EXP_MAN_A_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='race',
            name='EXP_MAN_B_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='race',
            name='EXP_WOMAN_A_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='race',
            name='EXP_WOMAN_B_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='race',
            name='OLD_WOMAN_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='race',
            name='YOUNG_MAN_A_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='race',
            name='YOUNG_MAN_B_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='race',
            name='YOUNG_WOMAN_A_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='race',
            name='YOUNG_WOMAN_B_FINISH',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
