# Generated by Django 2.0.1 on 2018-03-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_auto_20180304_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='ELITE_MAN_FINISH',
        ),
        migrations.RemoveField(
            model_name='race',
            name='ELITE_WOMAN_FINISH',
        ),
        migrations.RemoveField(
            model_name='race',
            name='EXP_MAN_A_FINISH',
        ),
        migrations.RemoveField(
            model_name='race',
            name='EXP_MAN_B_FINISH',
        ),
        migrations.RemoveField(
            model_name='race',
            name='EXP_WOMAN_A_FINISH',
        ),
        migrations.RemoveField(
            model_name='race',
            name='EXP_WOMAN_B_FINISH',
        ),
        migrations.RemoveField(
            model_name='race',
            name='OLD_WOMAN_FINISH',
        ),
        migrations.RemoveField(
            model_name='race',
            name='YOUNG_MAN_A_FINISH',
        ),
        migrations.RemoveField(
            model_name='race',
            name='YOUNG_MAN_B_FINISH',
        ),
        migrations.RemoveField(
            model_name='race',
            name='YOUNG_WOMAN_A_FINISH',
        ),
        migrations.RemoveField(
            model_name='race',
            name='YOUNG_WOMAN_B_FINISH',
        ),
    ]
