# Generated by Django 2.0.1 on 2018-03-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_auto_20180304_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='E20A_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='E20A_win_time_2',
        ),
        migrations.RemoveField(
            model_name='race',
            name='E20B_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='E20B_win_time_2',
        ),
        migrations.RemoveField(
            model_name='race',
            name='E21A_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='E21A_win_time_2',
        ),
        migrations.RemoveField(
            model_name='race',
            name='E21B_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='E21B_win_time_2',
        ),
        migrations.RemoveField(
            model_name='race',
            name='E21E_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='E21E_win_time_2',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K20A_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K20A_win_time_2',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K20B_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K20B_win_time_2',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K21A_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K21A_win_time_2',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K21B_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K21B_win_time_2',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K21E_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K21E_win_time_2',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K55_win_time_1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='K55_win_time_2',
        ),
    ]
