# Generated by Django 2.0.1 on 2018-03-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_auto_20180304_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='stages',
        ),
        migrations.AddField(
            model_name='race',
            name='stages',
            field=models.ManyToManyField(to='league.Stage'),
        ),
    ]
