# Generated by Django 2.0.1 on 2018-03-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_auto_20180304_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='selected_players',
            field=models.ManyToManyField(blank=True, to='league.Participation'),
        ),
    ]
