# Generated by Django 2.0.2 on 2018-03-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_auto_20180304_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stage_1_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='stage_2_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
