# Generated by Django 2.0.2 on 2018-03-09 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_auto_20180308_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='disqualification_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
