# Generated by Django 2.0.2 on 2018-03-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_participation_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
