# Generated by Django 2.0.1 on 2018-10-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_auto_20180404_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='finish_time_3',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='score_3',
        ),
        migrations.AlterField(
            model_name='participation',
            name='group',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1),
        ),
    ]
