# Generated by Django 2.0.2 on 2019-05-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_auto_20190416_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='finish_time_3',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='score_3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stage_3_score',
        ),
    ]
