# Generated by Django 2.0.2 on 2020-02-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0031_auto_20191128_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='group',
            field=models.CharField(choices=[('1', '1')], default='1', max_length=1),
        ),
    ]
